### PR TITLE
SIP-0003: Remote Notifications and Triggers

### PR DESCRIPTION
**Pull request by 161chihuahuas**
https://github.com/bookchin/storj-sips/blob/master/sip-0003.md

### CODE REVIEW

**Comment by prestwich** [comment]
This basically enables almost any arbitrary application to use the Storj network as a network/transport layer right? 

Examples: 
- distributed instant messaging app using triggers to transmit text messages
- distributed event system where a single IoT device could trigger action across any number of devices based on small events (like a door opening)

Anyway, looks good from my side. 👍

**Comment by 161chihuahuas** [comment]
@super3 or @frdwrd can we merge this? I have links in the core 3.0.0 release docs that point to the storj/sips version of this doc (since this has been implemented) and don't want dead links. :)

**Comment by prestwich** [comment]
I say merge the heck out of it.

**Comment by phutchins** [comment]
I say merge as well. Look forward to it.

**Comment by super3** [comment]
ACK from my side.

Shawn

**Pull request merged**
